# Generated by Django 5.2.1 on 2025-05-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cc', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Cédula de Ciudadanía')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
