# Generated by Django 5.2.1 on 2025-05-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Local')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Local')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('cc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('contrasena', models.CharField(max_length=128)),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajador.local')),
            ],
        ),
    ]
