# Generated by Django 5.2.1 on 2025-05-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propina',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Servicio.servicio')),
            ],
        ),
    ]
